global:
  evaluation_interval: 15s
  scrape_interval:     15s

scrape_configs:
  -
    job_name: HostsMetrics
    dns_sd_configs:
      -
        names:
          - node-exporter
        port: 9100
        refresh_interval: 15s
        type: A

  -
    job_name: ContainerMetrics
    dns_sd_configs:
      -
        names:
          - cadvisor
        port: 8080
        refresh_interval: 15s
        type: A

  -
    job_name: RancherMetrics
    dns_sd_configs:
      -
        names:
          - prometheus-rancher-exporter
        port: 9173
        refresh_interval: 15s
        type: A

  -
    job_name: SkylineMetrics
    dns_sd_configs:
      -
        names:
          - skyline-metrics
        port: 3010
        refresh_interval: 60s
        type: A

  -
    job_name: prometheus
    static_configs:
      -
        targets:
          - '127.0.0.1:9090'

  -
    job_name: 'C8'
    metrics_path: '/csi-requesthandler/v1/prometheus/metrics'
    scheme: ${c8_url_scheme}

    static_configs:
      -
        targets:
          - ${c8_url_host}:${c8_url_port}

  -
    job_name: kafka
    metrics_path: /metrics
    dns_sd_configs:
      -
        names:
          - kafka.zookeeper-kafka.rancher.internal
        port: 7071
        type: A
    metric_relabel_configs:
      -
        # Rewrite the label name not starting with 'kafka_' to prefix job name
        source_labels: ['__name__']
        regex: '(^[^k].*)'
        target_label: '__name__'
        replacement: 'kafka_$1'

  -
    job_name: report-service
    metrics_path: /v1/report_service/metrics
    dns_sd_configs:
      -
        names:
          - report-service.c8-report-service.rancher.internal
        port: 8083
        type: A
    metric_relabel_configs:
      -
        # Rewrite the label name to prefix job name
        source_labels: ['__name__']
        regex: '(.*)'
        target_label: '__name__'
        replacement: 'report_service_$1'

  -
    job_name: change-logging-service
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      -
        names:
          - change-logging-microservice.change-logging.rancher.internal
        port: 8181
        type: A
    metric_relabel_configs:
      -
        # Rewrite the label name to prefix job name
        source_labels: ['__name__']
        regex: '(.*)'
        target_label: '__name__'
        replacement: 'change_logging_service_$1'

  -
    job_name: exporthub-service
    metrics_path: /v1/export_hub/metrics
    dns_sd_configs:
      -
        names:
          - exporthub-service.c8-exporthub-service.rancher.internal
        port: 8084
        type: A
    metric_relabel_configs:
      -
        # Rewrite the label name to prefix job name
        source_labels: ['__name__']
        regex: '(.*)'
        target_label: '__name__'
        replacement: 'exporthub_service_$1'

  -
    job_name: rancher
    metrics_path: /metrics
    dns_sd_configs:
      -
        names:
          - prometheus-rancher-exporter.pr.rancher.internal
        port: 9173
        type: A
