version: '2'
services:
  grafana:
    scale: 1
    health_check:
      port: 3000
      interval: 10000
      initializing_timeout: 60000
      unhealthy_threshold: 3
      request_line: GET /login HTTP/1.0
      healthy_threshold: 2
      response_timeout: 5000
