version: "2"
services:
    report-service:
        scale: 1
        health_check:
            port: 8083
            interval: 10000
            initializing_timeout: 60000
            unhealthy_threshold: 3
            request_line: GET /v2/check/health HTTP/1.0
            healthy_threshold: 2
            response_timeout: 5000
            strategy: none
