version: "2"
services:
    exporthub-service:
        scale: 1
        start_on_create: true
        health_check:
            port: 8084
            interval: 10000
            request_line: GET /v1/export_hub/healthcheck HTTP/1.0
            initializing_timeout: 60000
            unhealthy_threshold: 3
            healthy_threshold: 2
            response_timeout: 5000
            strategy: none
