version: '2'
services:
  change-logging-microservice:
    image: centricsoftware/change-logging-microservice:${CHANGE_LOGGING_DOCKER_IMAGE_VERSION}
    environment:
      APP_CENTRIC8_PASSWORD: ${CENTRIC_8_PASSWORD}
      APP_CENTRIC8_URL_PREFIX: ${CENTRIC_8_URL}
      APP_CENTRIC8_USER: ${CENTRIC_8_USERNAME}
      APP_DOMAIN_CONNECT_ATTEMPTS: ${CHANGE_LOG_DOMAIN_CONNECT_ATTEMPTS}
      APP_OAUTH2_CLIENTID: ${CHANGE_LOG_CLIENTID}
      APP_OAUTH2_CLIENTSECRET: ${CHANGE_LOG_CLIENTSECRET}
      APP_OAUTH2_ENDPOINT_TOKEN: ${CHANGE_LOG_OAUTH2_TOKEN_ENDPOINT}
      MONGO_TLS_ENABLE: ${MONGO_TLS_ENABLE}
      MONGO_TLS_KEYSTORE: ${MONGO_TLS_KEYSTORE}
      MONGO_TLS_KEYSTORE_PASSWORD: ${MONGO_TLS_KEYSTORE_PASSWORD}
      MONGO_TLS_INVALID_HOSTNAME_ALLOWED: ${MONGO_TLS_INVALID_HOSTNAME_ALLOWED}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: ${KAFKA_HOST_LIST}
      SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES: ${ZOOKEEPER_HOST_LIST}
      SPRING_CLOUD_STREAM_KAFKA_BINDER_AUTO_CREATE_TOPICS: ${KAFKA_AUTO_CREATE_TOPICS}
      SPRING_CLOUD_STREAM_KAFKA_BINDER_REPLICATION_FACTOR: ${KAFKA_REPLICATION_FACTOR}
      SPRING_CLOUD_STREAM_KAFKA_BINDER_CONFIGURATION_ISOLATION_LEVEL: read_committed
      SPRING_APPLICATION_JSON: '{"spring.cloud.stream.bindings.input.destination": "DistributionTopic"}'
      SPRING_DATA_MONGODB_URI: ${MONGO_DB_CONNECTION_URI}
      LOGGING_LEVEL_COM_CENTRICSOFTWARE: INFO
    ports:
      - 8181:8181/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_soft: c8-change-logging=true

