change-logging-microservice:
    scale: 1
    start_on_create: true
    health_check:
        port: 8181
        interval: 10000
        initializing_timeout: 60000
        unhealthy_threshold: 3
        request_line: GET /chg-log/v2/healthcheck HTTP/1.0
        healthy_threshold: 2
        response_timeout: 5000
        strategy: none
